services:
    sqlscript:
        image: jekkos/opensourcepos:sql-master
        command: /bin/sh -c 'exit 0'

    ospos:
        image: jekkos/opensourcepos:master
        restart: always
        depends_on:
            - db
        ports:
            - "127.0.0.1:80:80"
        networks:
            - app_net
        volumes:
            - uploads:/app/public/uploads
            - logs:/app/application/logs
        environment:
            CI_ENVIRONMENT: production
            FORCE_HTTPS: "false"
            PHP_TIMEZONE: UTC
            MYSQL_USERNAME: admin
            MYSQL_PASSWORD: pointofsale
            MYSQL_DB_NAME: ospos
            MYSQL_HOST_NAME: db

    sonarqube:
        image: sonarqube:latest
        depends_on:
            - db
        ports:
            - "9000:9000"
        networks:
            - app_net
        environment:
            SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
            SONAR_JDBC_USERNAME: sonar
            SONAR_JDBC_PASSWORD: sonar
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_logs:/opt/sonarqube/logs
            - sonarqube_extensions:/opt/sonarqube/extensions

    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: sonar
        networks:
            - app_net
        volumes:
            - postgresql_data:/var/lib/postgresql/data

volumes:
    uploads:
    logs:
    sonarqube_data:
    sonarqube_logs:
    sonarqube_extensions:
    postgresql_data:

networks:
    app_net:
